import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import usersRouter from "./users.js";
import clientsRouter from "./clients.js";
import hotelsRouter from "./hotels.js";
import quotationsRouter from "./quotations.js";
import transportRouter from "./transport.js";
import visaRouter from "./visa.js";
import flightsRouter from "./flights.js";
import flightSearchRouter from "./flight-search.js";
import gdsSettingsRouter from "./gds-settings.js";
import accountingRouter from "./accounting.js";
import dashboardRouter from "./dashboard.js";
import currencySettingsRouter from "./currency-settings.js";
import websiteConfigRouter from "./website-config.js";
import hotelInvoicesRouter from "./hotel-invoices.js";
import groupTicketsRouter from "./group-tickets.js";
import whatsappRouter from "./whatsapp.js";
import whatsappGroupsRouter from "./whatsapp-groups.js";
import whatsappInboxRouter from "./whatsapp-inbox.js";
import botRouter from "./bot.js";
import storageRouter from "./storage.js";
import bookingInquiriesRouter from "./booking-inquiries.js";
import packageInquiriesRouter from "./package-inquiries.js";
import portalRouter from "./portal.js";
import aiSettingsRouter from "./ai-settings.js";
import flightRequestsRouter from "./flight-requests.js";
import mediaLibraryRouter from "./media-library.js";
import vouchersRouter from "./vouchers.js";
import accountingReportsRouter from "./accounting-reports.js";
import financialYearRouter from "./financial-year.js";
import passengerDocumentsRouter from "./passenger-documents.js";
import localAirlineSettingsRouter from "./local-airline-settings.js";
import ocrSettingsRouter from "./ocr-settings.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(groupTicketsRouter);
router.use(bookingInquiriesRouter);
router.use(packageInquiriesRouter);
router.use(portalRouter);
router.use(aiSettingsRouter);
router.use(flightRequestsRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(clientsRouter);
router.use(hotelsRouter);
router.use(quotationsRouter);
router.use(transportRouter);
router.use(visaRouter);
router.use(flightsRouter);
router.use(flightSearchRouter);
router.use(gdsSettingsRouter);
router.use(hotelInvoicesRouter);
router.use(accountingRouter);
router.use(dashboardRouter);
router.use(currencySettingsRouter);
router.use(websiteConfigRouter);
router.use(whatsappRouter);
router.use(whatsappGroupsRouter);
router.use(whatsappInboxRouter);
router.use(botRouter);
router.use(mediaLibraryRouter);
router.use(vouchersRouter);
router.use(accountingReportsRouter);
router.use(financialYearRouter);
router.use(passengerDocumentsRouter);
router.use(localAirlineSettingsRouter);
router.use(ocrSettingsRouter);

export default router;
