-- Hotel DN Invoice entry table
-- Stores DN-format hotel voucher invoices with dual-currency (SAR + PKR) financials.
-- DN numbers auto-increment from DN-2187 onward (derived from max existing row).
CREATE TABLE IF NOT EXISTS "hotel_invoices" (
  "id" SERIAL PRIMARY KEY,
  "dn_number" TEXT NOT NULL UNIQUE,
  "invoice_date" DATE NOT NULL,
  "party_id" INTEGER,
  "vendor_id" INTEGER,
  "passenger_name" TEXT,
  "nationality" TEXT,
  "no_of_pax" INTEGER NOT NULL DEFAULT 1,
  "detail" TEXT,
  "voucher_type" TEXT,
  "option_date" DATE,
  "hotel_id" INTEGER,
  "hotel_name" TEXT,
  "hotel_view" TEXT,
  "room_type" TEXT,
  "bed_type" TEXT,
  "check_in" DATE,
  "check_out" DATE,
  "no_of_nights" INTEGER,
  "no_of_rooms" INTEGER NOT NULL DEFAULT 1,
  "reference" TEXT,
  "cnf_number" TEXT,
  "room_number" TEXT,
  "remarks" TEXT,
  "contact_number" TEXT,
  "receivable_sar" NUMERIC(14, 2),
  "payable_sar" NUMERIC(14, 2),
  "receivable_pkr" NUMERIC(14, 2),
  "payable_pkr" NUMERIC(14, 2),
  "income_head" TEXT NOT NULL DEFAULT 'Hotel Income',
  "salesman_id" INTEGER,
  "status" TEXT NOT NULL DEFAULT 'draft',
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMP NOT NULL DEFAULT NOW()
);
